### ISSUE TITLE
Dossier manquant

### ISSUE THREAD

**Issue by chdesplancke** [BridgeAPIs/PlayerTracker#1]
Hello ,

C'est normal que le dossier /realm/login n'existe pas ? :)
dans welcome_message.php le formulaire redirige vers realm/login mais le dossier n'existe pas

**Comment by zyuiop** [comment]
Il faut installer un .htaccess pour gérer la réécriture d'url

https://gist.github.com/philipptempel/4226750

**Comment by chdesplancke** [comment]
Désolé du retard mais merci sa marche nickel :D
